services:

    only-docs:
        image: onlyoffice/documentserver:latest
        container_name: only-docs    
        stdin_open: true
        tty: true
        ports:
            - "8500:80"
            - "8543:443"
        restart: unless-stopped
        volumes:
            - ./only/data:/var/www/onlyoffice/Data
            - ./only/logs:/var/log/onlyoffice 
            - ./only/lib:/var/lib/onlyoffice 
            - ./only/db:/var/lib/postgresql            
        environment:
            - JWT_SECRET=my_secret
            - JWT_ENABLED=true
            - JWT_HEADER=Authorization
            - JWT_IN_BODY=true
        entrypoint:
            - "sh"
            - "-c"
            - |
              echo 'patching https://github.com/ONLYOFFICE/DocumentServer/issues/2186...'
              find /var/www/onlyoffice/documentserver -name sdk-all-min.js -exec sed -E -i 's|(function +\w+\(\w+\) *\{ *function +\w+\(\)) *\{ *(\w+)\.open\((\w+),(\w+),(\w+)\);|\1{\nif (\4 \&\& \4.length > 5) {if (\4.substring(0, 5) == "http:") {\4 = \4.replace("http://", "https://");}};\n\2.open(\3,\4,\5);\n|' '{}' ';'
              echo 'done! starting server...'
              /app/ds/run-document-server.sh